// submitInfoForm.js
export const SUBMIT_INFO_FORM_FAIL =
  'SUBMIT_INFO_FORM_FAIL';
export const SUBMIT_INFO_FORM_PENDING =
  'SUBMIT_INFO_FORM_PENDING';
export const SUBMIT_INFO_FORM_SUCCESS =
  'SUBMIT_INFO_FORM_SUCCESS';